# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 867639d4e3cb7731bd4631a43551c29c3a811ed139e25c5b6b48273faa52367b0557cd2caade793e9c5578bb93937a76a876bd7487528ace5b56a8f5be990984

test:
  secret_key_base: 05b79c698bd187c35667f9b05ebe3cabcbf1ec4e103670cd46d1163265ce89f3aa8870550106d9a66ad411f424c287f24a5b8ffc48719770c79783ed3ce4006a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
